BEGIN;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    LOCATION TEXT 
);

INSERT INTO users (NAME, LOCATION)
VALUES ('Noor','Khanyounis');

INSERT INTO users (NAME, LOCATION)
VALUES ('Ahmed','Istanbul');


COMMIT;